# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# class TestGetvideo():
#   def setup_method(self, method):
#     self.driver = webdriver.Firefox()
#     self.vars = {}
  
#   def teardown_method(self, method):
#     self.driver.quit()
  
#   def test_getvideo(self):
#     self.driver.get("https://huggingface.co/spaces/NeuralInternet/Text-to-Video_Playground")
#     self.driver.set_window_size(1034, 1117)
#     self.driver.switch_to.frame(0)
#     self.driver.find_element(By.CSS_SELECTOR, ".scroll-hide").click()
#     self.driver.find_element(By.CSS_SELECTOR, ".scroll-hide").send_keys("cowboys in space")
#     self.driver.find_element(By.ID, "component-6").click()
#     self.driver.find_element(By.CSS_SELECTOR, "p").click()

# if __name__ == "__main__":
#   test = TestGetvideo()
#   test.setup_method("setup_method")
#   test.test_getvideo()
#   test.teardown_method("teardown_method")